// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzGFD0G3g9omf7HwAHmQgP3UPNWVNrhkU',
    appId: '1:405285466597:web:c88703a751a2e17feebf0c',
    messagingSenderId: '405285466597',
    projectId: 'lego-68f92',
    authDomain: 'lego-68f92.firebaseapp.com',
    databaseURL: 'https://lego-68f92-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lego-68f92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6vhdfKD5S26jklxeomS_UMQQ-Eex13qg',
    appId: '1:405285466597:android:9db48e085e7352b8eebf0c',
    messagingSenderId: '405285466597',
    projectId: 'lego-68f92',
    databaseURL: 'https://lego-68f92-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lego-68f92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtCzYxVYXz9bkHyjv1SC3mM1DUaVECDOk',
    appId: '1:405285466597:ios:59d0e3d72a224986eebf0c',
    messagingSenderId: '405285466597',
    projectId: 'lego-68f92',
    databaseURL: 'https://lego-68f92-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lego-68f92.appspot.com',
    iosBundleId: 'com.example.ayuntamiento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtCzYxVYXz9bkHyjv1SC3mM1DUaVECDOk',
    appId: '1:405285466597:ios:59d0e3d72a224986eebf0c',
    messagingSenderId: '405285466597',
    projectId: 'lego-68f92',
    databaseURL: 'https://lego-68f92-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lego-68f92.appspot.com',
    iosBundleId: 'com.example.ayuntamiento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIIbC-BM8KgYQrnBv_ileMnPVHGrWAfRU',
    appId: '1:405285466597:web:5380ccdec4971a41eebf0c',
    messagingSenderId: '405285466597',
    projectId: 'lego-68f92',
    authDomain: 'lego-68f92.firebaseapp.com',
    databaseURL: 'https://lego-68f92-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lego-68f92.appspot.com',
  );
}
